"""Blue Team brief. Same findings as CVINFERNO, opposite face."""

from __future__ import annotations

from tenaille import PRODUCT, TAGLINE
from tenaille.confirmation import Ceiling, Finding, validate_brief
from tenaille.confirmation.tiers import evaluate_inventory
from tenaille.intel.lookup import lookup_cve
from tenaille.intel.models import CveRecord


def _records() -> dict[str, CveRecord]:
    return {
        "CVE-2024-6387": lookup_cve("CVE-2024-6387"),
        "CVE-2023-38408": lookup_cve("CVE-2023-38408"),
    }


def render_blue_brief(inventory: dict) -> str:
    findings = evaluate_inventory(inventory, _records())
    host = inventory["host"]
    lines = [
        f"Generated by {PRODUCT} / CVBASTION (sample)",
        f"{PRODUCT} — {TAGLINE}",
        f"Host: {host.get('id')} (synthetic lab fixture)",
        f"Exposure: {host.get('exposure', 'unspecified')}",
        "Confirmation ceiling for every finding below: version_match",
        "Priority here is for a lab image, not an internet incident.",
        "",
        "Leadership read",
        "  Two hypotheses share one inventory. Neither has been shown on a",
        "  running socket beyond the version and the config field that were",
        "  written down. Spend the lab hour on patch level and agent-forwarding",
        "  policy. Do not brief this as an active compromise.",
        "",
        "Remediation table",
        "  Pri  CVE             Pair      Lab meaning",
        "  ---  --------------  --------  ---------------------------",
    ]
    if not findings:
        lines.append("  (no starter finding — nothing to prioritize)")
    for finding in findings:
        lines.append(
            f"  {finding.priority:<3}  {finding.cve_id:<14}  {finding.role.split('—')[0].strip():<8}  "
            "version_match on a lab fixture"
        )
    lines.append("")
    lines.append("What P1 / P2 / P3 mean in this sample")
    lines.append("  P1  Internet-facing, and KEV or a high EPSS score, with evidence.")
    lines.append("      A lab-only host cannot land here. Raw CVSS cannot put it here either.")
    lines.append("  P2  Catalog weight (for example a KEV flag in the fixture) on a lab host.")
    lines.append("  P3  Hygiene. Worth doing before the image is cloned. Not an incident.")
    lines.append("")
    for finding in findings:
        lines.extend(_control_block(finding))
    lines.extend(
        [
            "What done means for the host",
            "  Re-run HARBNGR against the same lab image after the change window.",
            "  Every starter finding above should either fall out of the upstream",
            "  range or carry a named vendor advisory, and agent forwarding should",
            "  be off or exception-listed. The new brief should still refuse to",
            "  say the old image was compromised.",
            "",
        ]
    )
    text = "\n".join(lines).rstrip() + "\n"
    validate_brief(text, Ceiling.VERSION_MATCH)
    return text


def _control_block(finding: Finding) -> list[str]:
    return [
        f"{finding.cve_id}  ↔  {finding.role}",
        f"  Priority: {finding.priority}    Ceiling: {finding.ceiling.value}",
        f"  Control: {finding.blue_control}",
        f"  Detection: {finding.detection}",
        f"  Remediation: {finding.remediation}",
        f"  Done for this item: {finding.done_means}",
        f"  Still true: {finding.not_claimed}",
        "",
    ]
