"""Version match must not be narrated as compromise."""

import unittest

from tenaille.confirmation import Ceiling, ConfirmationError, validate_brief
from tenaille.confirmation.tiers import context_priority, evaluate_inventory, version_matches_record
from tenaille.cvinferno import render_red_brief
from tenaille.cvbastion import render_blue_brief
from tenaille.harbngr.recon import load_inventory
from tenaille.intel.lookup import lookup_cve
from tenaille.paths import DEFAULT_INVENTORY, EXAMPLES


class ConfirmationTests(unittest.TestCase):
    def test_version_match_rejects_exploited_claim(self):
        bad = (
            "Generated by Tenaille / CVINFERNO (sample)\n"
            "The lab host was exploited via the OpenSSH race.\n"
        )
        with self.assertRaises(ConfirmationError) as caught:
            validate_brief(bad, Ceiling.VERSION_MATCH)
        self.assertIn("exploited", str(caught.exception).lower())

    def test_sample_briefs_stay_inside_the_ceiling(self):
        inventory = load_inventory(DEFAULT_INVENTORY)
        red = render_red_brief(inventory)
        blue = render_blue_brief(inventory)
        validate_brief(red, Ceiling.VERSION_MATCH)
        validate_brief(blue, Ceiling.VERSION_MATCH)
        for text in (red, blue):
            self.assertIn("version_match", text)
            self.assertNotIn("exploited", text.lower())
            self.assertNotRegex(text.lower(), r"exploit succeeded")

        findings = evaluate_inventory(
            inventory,
            {
                "CVE-2024-6387": lookup_cve("CVE-2024-6387"),
                "CVE-2023-38408": lookup_cve("CVE-2023-38408"),
            },
        )
        self.assertEqual(len(findings), 2)
        self.assertTrue(all(item.ceiling is Ceiling.VERSION_MATCH for item in findings))
        self.assertTrue(all(item.version_match for item in findings))

    def test_upstream_ranges(self):
        regre = lookup_cve("CVE-2024-6387")
        agent = lookup_cve("CVE-2023-38408")
        self.assertTrue(version_matches_record("OpenSSH_8.9p1", regre))
        self.assertTrue(version_matches_record("9.7p1", regre))
        self.assertFalse(version_matches_record("9.8p1", regre))
        self.assertTrue(version_matches_record("8.9p1", agent))
        self.assertFalse(version_matches_record("9.3p2", agent))
        self.assertFalse(version_matches_record("9.6p1", agent))

    def test_lab_exposure_cannot_be_p1_from_cvss_alone(self):
        self.assertEqual(
            context_priority(
                kev_listed=True,
                epss_score=None,
                exposure="lab-only",
                ceiling=Ceiling.VERSION_MATCH,
            ),
            "P2",
        )
        self.assertEqual(
            context_priority(
                kev_listed=False,
                epss_score=None,
                exposure="lab-only",
                ceiling=Ceiling.VERSION_MATCH,
            ),
            "P3",
        )
        self.assertEqual(
            context_priority(
                kev_listed=True,
                epss_score=0.9,
                exposure="internet-facing",
                ceiling=Ceiling.TEMPLATE_VERIFIED,
            ),
            "P1",
        )

    def test_windows_fixture_invents_nothing(self):
        inventory = load_inventory(EXAMPLES / "lab-win-01.json")
        red = render_red_brief(inventory)
        self.assertIn("will not invent", red)
        validate_brief(red, Ceiling.VERSION_MATCH)


if __name__ == "__main__":
    unittest.main()
