"""Red Team brief from an inventory and the starter findings.

Language is hypothesis, impact, and what is not claimed. There is no
procedure for triggering a bug.
"""

from __future__ import annotations

from tenaille import PRODUCT, TAGLINE
from tenaille.confirmation import Ceiling, Finding, validate_brief
from tenaille.confirmation.tiers import evaluate_inventory
from tenaille.intel.lookup import lookup_cve
from tenaille.intel.models import CveRecord


def _records() -> dict[str, CveRecord]:
    return {
        "CVE-2024-6387": lookup_cve("CVE-2024-6387"),
        "CVE-2023-38408": lookup_cve("CVE-2023-38408"),
    }


def render_red_brief(inventory: dict) -> str:
    findings = evaluate_inventory(inventory, _records())
    host = inventory["host"]
    lines = [
        f"Generated by {PRODUCT} / CVINFERNO (sample)",
        f"{PRODUCT} — {TAGLINE}",
        f"Host: {host.get('id')} (synthetic lab fixture)",
        f"Exposure: {host.get('exposure', 'unspecified')}",
        "Confirmation ceiling for every finding below: version_match",
        "This brief does not claim compromise.",
        "",
        "How to read difficulty",
        "  Easy   — what a student can see in the inventory alone.",
        "  Medium — which evidence is still missing, and why raw CVSS misleads.",
        "  Hard   — residual uncertainty a reviewer would still have to retire.",
        "None of the three levels is a procedure.",
        "",
    ]
    if not findings:
        lines.append(
            "No starter path matches this fixture. CVINFERNO will not invent a CVE "
            "to fill the page."
        )
    for finding in findings:
        lines.extend(_path_block(finding))
    lines.extend(
        [
            "Shared limit",
            "  Both paths stop at version_match. Active verification (is the service",
            "  reachable, does the banner agree) and template verification are later",
            "  tiers. They were not run.",
            "",
        ]
    )
    text = "\n".join(lines).rstrip() + "\n"
    validate_brief(text, Ceiling.VERSION_MATCH)
    return text


def _path_block(finding: Finding) -> list[str]:
    match = "upstream version is inside the published range" if finding.version_match else "upstream version is not inside the published range"
    return [
        f"{finding.role}",
        f"  CVE: {finding.cve_id} — {finding.title}",
        f"  Ceiling: {finding.ceiling.value}",
        f"  Context priority: {finding.priority} (KEV, EPSS, and exposure — not raw CVSS)",
        f"  Version comparison: {match}",
        "",
        "  Easy",
        f"    Evidence: {finding.evidence}",
        f"    Why it matters: {finding.why_it_matters}",
        "",
        "  Medium",
        "    Missing evidence: no second collection of the banner, no check that the",
        "    service is reachable from anywhere, no distro changelog. A high CVSS",
        "    number does not promote the ceiling. Path B stays post-foothold even",
        "    when the version number matches: the public issue depends on an agent",
        "    being forwarded, and this inventory does not record that happening.",
        "",
        "  Hard",
        "    A reviewer still does not know whether the packaged build already",
        "    contains a backport, whether LoginGraceTime or agent policy differs",
        "    on disk from this JSON, or whether the lab image was replaced since",
        "    the fixture was written. Those gaps stay open on purpose.",
        f"    {finding.not_claimed}",
        "",
    ]
